### ISSUE TITLE
not compatible with PE2017

### ISSUE THREAD

**Issue by vchepkov** [acidprime/exports#8]
I noticed in PE2017 command doesn't return anything
# puppet node exports 
Name                                      Exports

**Comment by natemccurdy** [comment]
@vchepkov It is working for me on PE 2017.3.2. Are you sure there are any resources being exported? Out of the box, there aren't any.

Here's an example where I'm exporting a simple `notify` resource. I'm using PQL to find the export first, then using @acidprime 's module to show the same thing:

```
[root@pe-201732-master ~]# puppet query 'resources {exported = true}'
[
  {
    "tags": [
      "class",
      "notify",
      "default",
      "node"
    ],
    "file": "/etc/puppetlabs/code/environments/production/manifests/site.pp",
    "type": "Notify",
    "title": "this is exported",
    "line": 4,
    "resource": "7d1137c516a51454ea7a15417750730afa0990d2",
    "environment": "production",
    "certname": "pe-201732-master.puppetdebug.vlan",
    "parameters": {},
    "exported": true
  }
]

[root@pe-201732-master ~]#puppet node exports
Name                                      Exports
pe-201732-master.puppetdebug.vlan         Notify[this is exported]
```

**Comment by vchepkov** [comment]
Yep, it works now, thank you. It didn't work a year ago though.
